name: 'Artifcact Demo'

on: push

jobs:
  job_1:
    name: Upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: "Create Local File"
        run: |
            echo "Archer is awesome!" > my_file.txt
        
      - uses: actions/upload-artifact@v2
        with:
            name: file
            path: my_file.txt
            retention-days: 5
  
  job_2:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v2
        with:
            name: file
      - run: cat my_file.txt
